# Docker-compose that runs the production.
version: "3.4"

networks:
  backend:
  judgezero:

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:

  picspy-front:
    image: registry.qtmsheep.com/vagahbond/picspy/frontend:latest
    ports:
      - "${FRONTEND_EXTERNAL_PORT}:80"

  picspy-api:
    image: registry.qtmsheep.com/vagahbond/picspy/api:latest
    ports:
      - "${API_EXTERNAL_PORT}:${API_INTERNAL_PORT}"
    depends_on: 
      - picspy-mongo
    environment:
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      API_INTERNAL_PORT: ${API_INTERNAL_PORT}
      API_EXTERNAL_HOST: ${API_EXTERNAL_HOST}
      API_EXTERNAL_PORT: ${API_EXTERNAL_PORT}
      SECRET_JWT_KEY: ${SECRET_JWT_KEY}
      JUDGEZERO_URL: ${JUDGEZERO_URL}
      JUDGEZERO_PORT: ${JUDGEZERO_PORT}
    networks: 
      - backend
      - judgezero

  picspy-mongo:
    restart: always
    image: mongo:4.2.0
    volumes:
      - picspy-data:/data/db
    ports: 
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks: 
      - backend

  judge-server:
    image: judge0/judge0:1.13.0
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always
    networks: 
      - judgezero

  judge-workers:
    image: judge0/judge0:1.13.0
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always
    networks: 
      - judgezero

  judge-db:
    image: postgres:13.0
    env_file: judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always
    networks: 
      - judgezero

  judge-redis:
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    volumes:
      - redis-data:/data
    <<: *default-logging
    restart: always
    networks: 
      - judgezero

volumes:
  postgres-data:
  redis-data:
  picspy-data: