apiVersion: apps/v1
kind: Deployment
metadata:
  name: picspy-godbox
  labels:
    app: godbox
  namespace: picspy
spec:
  selector:
    matchLabels:
      app: godbox
  template:
    metadata:
      labels:
        app: godbox
    spec:
      imagePullSecrets:
        - name: vagahbond-registry-creds

      containers:
        - name: picspy-godbox
          image: registry.qtmsheep.com/vagahbond/picspy/picspy-godbox:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
          envFrom:
            - configMapRef:
                name: picspy-configmap