apiVersion: v1
kind: Service
metadata:
  name: picspy-godbox-service
  namespace: picspy
  labels:
    app: godbox
spec:
  selector:
      app: godbox
  ports:
    - name: picspy-godbox-port
      port: 8080
      targetPort: 8080