apiVersion: apps/v1
kind: Deployment
metadata:
  name: picspy-frontend
  labels:
    app: frontend
  namespace: picspy
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: vagahbond-registry-creds

      
      containers:
      - name: picspy-front
        image: registry.qtmsheep.com/vagahbond/picspy/frontend:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 90
        envFrom:
          - configMapRef:
              name: picspy-configmap