apiVersion: v1
kind: Service
metadata:
  name: picspy-frontend-service
  namespace: picspy
  labels:
    app: frontend
spec:
  selector:
      app: frontend
  ports:
    - name: picspy-frontend-port
      port: 3080
      targetPort: 90