apiVersion: apps/v1
kind: Deployment
metadata:
  name: picspy-mongo
  labels:
    app: picspy
  namespace: picspy
spec:
  selector:
    matchLabels:
      app: picspy
  template:
    metadata:
      labels:
        app: picspy
    spec:

      containers:

        - name: picspy-mongo
          image: mongo:4.2.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: picspy-data
          envFrom:
            - configMapRef:
                name: picspy-configmap

      volumes:
        - name: picspy-data
          persistentVolumeClaim:
            claimName: picspy-data

      
        
