apiVersion: apps/v1
kind: Deployment
metadata:
  name: picspy-minio
  labels:
    app: picspy
  namespace: picspy
spec:
  selector:
    matchLabels:
      app: picspy
  template:
    metadata:
      labels:
        app: picspy
    spec:

      containers:

        - name: picspy-minio
          image: minio/minio
          imagePullPolicy: Always
          command: ["server"]
          args: ["/data"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 9000
          volumeMounts:
              - mountPath: /data
                name: picspy-minio
          envFrom:
          - configMapRef:
              name: picspy-configmap

      volumes:

        - name: picspy-minio
          persistentVolumeClaim:
            claimName: picspy-minio

      
        
