apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: picspy-data
  name: picspy-data
  namespace: picspy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
