apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: picspy-ingress
  namespace: picspy
  # annotations:
    # kubernetes.io/ingress.class: traefik
    # ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app: picspy
  
spec:
  rules:
    - host: "picspy.vagahbond.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: picspy-frontend-service
                port:
                  number: 3080
    - host: "api.picspy.vagahbond.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: picspy-api-service
                port:
                  number: 3000
