kind: ConfigMap 
apiVersion: v1 
metadata:
  name: picspy-configmap
  namespace: picspy
data:
  API_EXTERNAL_HOST: https://api.picspy.vagahbond.com
  # API_EXTERNAL_PORT: "80"
  API_INTERNAL_PORT: "3000"
  API_INTERNAL_HOST: http://picspy-api-service
  REACT_APP_API_EXTERNAL_HOST: https://api.picspy.vagahbond.com
  REACT_APP_FRONTEND_EXTERNAL_PORT: "80"
  MONGO_USER: docker
  MONGO_DB: picspy
  MONGO_PASSWORD: password
  MONGO_HOST: picspy-database-service
  MONGO_PORT: "27017"
  MONGO_INITDB_ROOT_USERNAME: docker
  MONGO_INITDB_ROOT_PASSWORD: password
  GODBOX_INTERNAL_PORT: "8080"
  GODBOX_INTERNAL_HOST: picspy-godbox-service
  GODBOX_URL: picspy-godbox-service
  GODBOX_PORT: "8080"
  MINIO_INTERNAL_ENDPOINT: minio.minio.svc.cluster.local
  MINIO_EXTERNAL_ENDPOINT: minio.picspy.vagahbond.com
  API_MAX_PAYLOAD_SIZE: "1000000"
  MINIO_INTERNAL_PORT: "9000"
  MINIO_EXTERNAL_PORT: "80"
  MINIO_ACCESS_KEY: miniokey
  MINIO_SECRET_KEY: miniosecret
  USESSL: 'false'


