apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: picspy-minio
  name: picspy-minio
  namespace: picspy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
