apiVersion: apps/v1
kind: Deployment
metadata:
  name: picspy-api
  labels:
    app: api
  namespace: picspy
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: vagahbond-registry-creds

      
      containers:
      - name: picspy-api
        image: registry.qtmsheep.com/vagahbond/picspy/api:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: picspy-configmap